[toolchain]
anchor_version = "0.32.1"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
payroll = "HoDcH6ocPxqHt5yEQGPAGrJZ9PgMp8LzU5gnEVBxNne6"

[programs.localnet]
payroll = "HoDcH6ocPxqHt5yEQGPAGrJZ9PgMp8LzU5gnEVBxNne6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.payroll.json -t 1000000 \"tests/payroll/**/*.ts\""
